// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqk9W1YIeHMETGLmoltFJVDaJG0YtE2q8',
    appId: '1:808246572772:web:803e16427a031430611ef1',
    messagingSenderId: '808246572772',
    projectId: 'social-media-cd995',
    authDomain: 'social-media-cd995.firebaseapp.com',
    storageBucket: 'social-media-cd995.appspot.com',
    measurementId: 'G-RT0NT226ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-rlF-u-ptc98YBRzvhRVaPU65drkLuw',
    appId: '1:808246572772:android:ba84796655c2501a611ef1',
    messagingSenderId: '808246572772',
    projectId: 'social-media-cd995',
    storageBucket: 'social-media-cd995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqqIzw2ICRbP6IxKBlR6YAXTJMbWEPmCQ',
    appId: '1:808246572772:ios:4ad9cdba4e67a73b611ef1',
    messagingSenderId: '808246572772',
    projectId: 'social-media-cd995',
    storageBucket: 'social-media-cd995.appspot.com',
    iosBundleId: 'com.babak.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqqIzw2ICRbP6IxKBlR6YAXTJMbWEPmCQ',
    appId: '1:808246572772:ios:902cf48f042bed87611ef1',
    messagingSenderId: '808246572772',
    projectId: 'social-media-cd995',
    storageBucket: 'social-media-cd995.appspot.com',
    iosBundleId: 'com.babak.socialMedia.RunnerTests',
  );
}
